name: notification_master
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.11.0
  google_sign_in: ^5.2.3
  firebase_auth: ^3.3.5
  font_awesome_flutter: ^9.2.0
  flutter_local_notifications: ^9.2.0
  firebase_messaging: ^11.2.5
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true