// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZgTBjqztbJlRNh2SS2YMipe03EgDN144',
    appId: '1:162068921980:android:339e37105bf56fde5893f9',
    messagingSenderId: '162068921980',
    projectId: 'portfolio-2d7bb',
    databaseURL: 'https://portfolio-2d7bb.firebaseio.com',
    storageBucket: 'portfolio-2d7bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADjZ5A_mXmgtWcI9wOMRh37Z6OCPqyIFI',
    appId: '1:162068921980:ios:44a7c7bc915ba8a25893f9',
    messagingSenderId: '162068921980',
    projectId: 'portfolio-2d7bb',
    databaseURL: 'https://portfolio-2d7bb.firebaseio.com',
    storageBucket: 'portfolio-2d7bb.appspot.com',
    iosClientId: '162068921980-74o4bi054t68ah19dmv8tmqqu2ek7cv3.apps.googleusercontent.com',
    iosBundleId: 'com.yashdhume.notification',
  );
}
